name: workshop
channels:
- pytorch
dependencies:
- python=3.9
- pip
- pip:
  - livelossplot
  - torchsummary
  - numpy
  - torch
  - torchvision
  - torchaudio
  - notebook
  - ipywidgets
  - pandas
  - pillow
  - tqdm
  - matplotlib
